### ISSUE TITLE
ATM und Tür Problem

### ISSUE THREAD

**Issue by FLouwz34** [m4uk3/Altv-Roleplay-German#9]
Hey, Chef. Ich kann leider bei keinem ATM irgendwas abheben, einzahlen etc. ich klicke drauf, passiert aber nie etwas. Ausserdem, kann man als PDler die PD Türen nicht öffnen und schliessen, oder mache ich was falsch?

**Comment by m4uk3** [comment]
Türen brauchst du natürlich nen schlüssel dafür denn du im pd shop kaufen kannst wei gerade net ob der in der sql schon drin ist
atm schua ich

**Comment by m4uk3** [comment]
https://discord.gg/VDxBRXcseC
ist auch in der readme jetzt neu
